/*
  # Amsterdam - Bölüm 5: Pizza Mekanları
*/

INSERT INTO venues (food_category_id, name, website_url, map_link, image, lat, lng, google_rating, google_review_count, mentor_note, must_order, mentor_tricks, sort_order)
SELECT 
  (SELECT id FROM food_categories WHERE city_id = (SELECT id FROM cities WHERE slug = 'amsterdam') AND slug = 'pizza'),
  v.name, v.website, v.map_link, v.image, v.lat, v.lng, v.rating, v.review_count, v.mentor_note, v.must_order, v.mentor_tricks, v.sort_order
FROM (VALUES
  ('La Perla', 'https://pizzeriaperla.nl/', 'https://maps.google.com/?q=52.375,4.88', '/venues/amsterdam/laperla.jpg', 52.375, 4.88, 4.6, 2500, 
   'Jordaan bölgesinin kalbinde, odun fırınında pişen otantik Napoli pizzalarıyla ünlü. Küçük, samimi ve her zaman kalabalık.', 
   'Margherita D.O.P.', 
   ARRAY['🔥 Odun fırınının hemen karşısındaki masalardan birini kapmaya çalışın.', '🍷 Genellikle rezervasyon almazlar, erken gidip sıraya girmek gerekebilir.', '😋 Hamuru ve malzemelerin kalitesi gerçekten fark yaratıyor.'], 
   1),
  ('Mastino V', 'https://www.mastinoamsterdam.com/', 'https://maps.google.com/?q=52.367,4.895', '/venues/amsterdam/mastino.jpg', 52.367, 4.895, 4.5, 3800, 
   'Roman tarzı al götür pizza. Düz tepsi pizzalar, lezzetli ve uygun fiyatlı. Yerel halkın favorisi.', 
   'Mortadella Pizza', 
   ARRAY['🍕 Pizza al taglio (dilim pizza) konsepti, dilediğiniz kadar alabilirsiniz.', '⚡ Çok hızlı servis, sokakta yürürken yemek için ideal.', '💰 Fiyatlar çok makul, öğrenci dostu.'], 
   2),
  ('Sotto', 'https://www.sottopizzeria.nl/', 'https://maps.google.com/?q=52.359,4.892', '/venues/amsterdam/sotto.jpg', 52.359, 4.892, 4.6, 2200, 
   'Şık ve modern İtalyan pizzacısı. Hem pizzaları hem de ambiyansı harika.', 
   'Tartufo Pizza', 
   ARRAY['🍄 Trüf pizzaları meşhur, kesinlikle deneyin.', '🍝 Pasta menüleri de çok iyi.', '🌟 Romantik bir akşam yemeği için ideal.'], 
   3),
  ('Dignita', 'https://www.dignita.nl/', 'https://maps.google.com/?q=52.358,4.89', '/venues/amsterdam/dignita.jpg', 52.358, 4.89, 4.4, 5600, 
   'Sosyal bir işletme, kârın bir kısmını hayır işlerine ayırıyorlar. Pizzaları da lezzetli, atmosfer keyifli.', 
   'Burrata Pizza', 
   ARRAY['💚 Sosyal sorumluluk projeleri destekleniyor.', '☕ Kahve ve brunch menüleri de harika.', '📚 Rahat oturmaya uygun, laptop ile çalışabilirsiniz.'], 
   4),
  ('Pazzi', 'https://www.pazzi.pizza/', 'https://maps.google.com/?q=52.374,4.898', '/venues/amsterdam/pazzi.jpg', 52.374, 4.898, 4.3, 1900, 
   'Robotların pizza yaptığı fütüristik konsept! Evet, doğru duydunuz. Hem eğlenceli hem lezzetli.', 
   'Pepperoni Pizza', 
   ARRAY['🤖 Robotları izlemek gerçekten eğlenceli bir deneyim.', '⚡ Çok hızlı hazırlanıyor, sadece 5 dakika.', '🆕 Yeni ve özgün bir deneyim arayanlar için.'], 
   5),
  ('Pizzeria Ristorante Venezia', 'https://www.ristorantevenezia.nl/', 'https://maps.google.com/?q=52.363,4.891', '/venues/amsterdam/venezia.jpg', 52.363, 4.891, 4.5, 3400, 
   'Klasik İtalyan aile restoranı atmosferi. Pizza ve pasta çeşitleri geniş.', 
   'Quattro Formaggi', 
   ARRAY['🇮🇹 İtalyan personel, otantik deneyim.', '👨‍👩‍👧 Aile dostu, çocuklarla gidilebilir.', '🍷 İtalyan şarap seçkisi zengin.'], 
   6),
  ('Napolicano', 'https://www.napolicano.com/', 'https://maps.google.com/?q=52.371,4.885', '/venues/amsterdam/napolicano.jpg', 52.371, 4.885, 4.7, 1600, 
   'Napoli usulü pizza konusunda uzman, hamur fermantasyonu mükemmel.', 
   'Marinara', 
   ARRAY['🍕 Hamur 72 saat fermente ediliyor, çok hafif ve lezzetli.', '🥫 Domates sosu İtalyadan getiriliyor.', '👨‍🍳 Pizzaiolo Napolili, işini çok iyi biliyor.'], 
   7),
  ('Doughnut Project', 'https://www.doughnutproject.nl/', 'https://maps.google.com/?q=52.365,4.883', '/venues/amsterdam/doughnut-pizza.jpg', 52.365, 4.883, 4.4, 2700, 
   'Aslında bir doughnut yeri ama sourdough pizzaları da inanılmaz lezzetli!', 
   'Sourdough Pizza', 
   ARRAY['🍩 Tatlı olarak doughnut almayı unutmayın.', '🍞 Ekşi maya hamurunun tadı benzersiz.', '🎨 Dekorasyon çok şık ve Instagramlık.'], 
   8),
  ('Dutch Weed Burger Joint', 'https://dutchweedburger.com/', 'https://maps.google.com/?q=52.372,4.897', '/venues/amsterdam/weed.jpg', 52.372, 4.897, 4.2, 3100, 
   'Vegan pizza ve burgerler. Adından korkmayın, THC yok! Weed deniz yosunu anlamında.', 
   'Vegan Margherita', 
   ARRAY['🌱 %100 bitkisel, et sevmeyenler için cennet.', '🌊 Deniz yosunu bazlı protein kullanılıyor.', '♻️ Sürdürülebilir ve çevre dostu.'], 
   9),
  ('Renatos', 'https://www.renatos.nl/', 'https://maps.google.com/?q=52.36,4.886', '/venues/amsterdam/renatos.jpg', 52.36, 4.886, 4.5, 2400, 
   'Geleneksel İtalyan pizzası, cömert porsiyonlar.', 
   'Prosciutto e Funghi', 
   ARRAY['📏 Pizzalar çok büyük, paylaşmayı düşünebilirsiniz.', '🍝 Anti pasti tabakları da harika.', '⏰ Akşam yemeği için rezervasyon şart.'], 
   10),
  ('Gusto Italiano', 'https://www.gusto-italiano.nl/', 'https://maps.google.com/?q=52.376,4.894', '/venues/amsterdam/gusto.jpg', 52.376, 4.894, 4.6, 1800, 
   'Samimi, aile işletmesi bir pizzacı. Her şey ev yapımı.', 
   'Gusto Special', 
   ARRAY['👪 Sahipleri çok sıcakkanlı ve misafirperver.', '🎵 Canlı İtalyan müziği bazen çalınıyor.', '💝 Fiyatlar uygun, kalite yüksek.'], 
   11)
) AS v(name, website, map_link, image, lat, lng, rating, review_count, mentor_note, must_order, mentor_tricks, sort_order)
ON CONFLICT DO NOTHING;
