/*
  # Add Paris Remaining Food Venues (55 venues)

  1. New Data
    - 11 Coffee venues
    - 11 Bistro venues  
    - 11 Crepe venues
    - 11 Michelin venues
    - 11 Local specialty venues
    
  2. Notes
    - Completes Paris gold standard
    - Total: 66 venues (6 categories x 11)
*/

DO $$
DECLARE
  v_coffee_id uuid;
  v_bistro_id uuid;
  v_crepe_id uuid;
  v_michelin_id uuid;
  v_local_id uuid;
BEGIN
  -- Get category IDs
  SELECT id INTO v_coffee_id FROM food_categories WHERE city_id = (SELECT id FROM cities WHERE slug = 'paris') AND slug = 'kahve';
  SELECT id INTO v_bistro_id FROM food_categories WHERE city_id = (SELECT id FROM cities WHERE slug = 'paris') AND slug = 'bistro';
  SELECT id INTO v_crepe_id FROM food_categories WHERE city_id = (SELECT id FROM cities WHERE slug = 'paris') AND slug = 'crepe';
  SELECT id INTO v_michelin_id FROM food_categories WHERE city_id = (SELECT id FROM cities WHERE slug = 'paris') AND slug = 'michelin';
  SELECT id INTO v_local_id FROM food_categories WHERE city_id = (SELECT id FROM cities WHERE slug = 'paris') AND slug = 'yerel-lezzetler';

  -- COFFEE VENUES (11)
  INSERT INTO venues (food_category_id, name, image, map_link, website_url, lat, lng, google_rating, google_review_count, mentor_note, reviews_summary, must_order, sort_order) VALUES
    (v_coffee_id, 'Ten Belles', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800', 'https://maps.google.com/?q=Ten+Belles+Paris', 'https://www.tenbelles.com/', 48.87, 2.365, 4.5, 1500, 'Paris''in üçüncü dalga kahve sahnesinin öncülerinden. Canal Saint-Martin kenarındaki küçük dükkanları çok sevimli.', ARRAY['☕ Kahveleri her zaman mükemmel kavrulmuş.', '🥪 Öğle yemeği için sandviçleri çok lezzetli.', '🚶‍♂️ Kahvenizi alıp kanal kenarında yürümek harika.'], 'Flat White', 1),
    (v_coffee_id, 'KB CaféShop', 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800', 'https://maps.google.com/?q=KB+CaféShop+Paris', 'https://www.kbcafeshop.com/', 48.868, 2.354, 4.6, 1200, 'Marais''deki harika bir specialty kahve dükkanı.', ARRAY['☕ Barista''lar çok bilgili.', '🥐 Kahve yanı hamur işleri taze.', '📚 Rahat ve çalışmaya uygun.'], 'Cappuccino', 2),
    (v_coffee_id, 'Télescope Café', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800', 'https://maps.google.com/?q=Télescope+Café+Paris', 'https://www.telescopecafe.com/', 48.866, 2.341, 4.7, 900, 'Küçük ama harika bir specialty coffee dükkanı.', ARRAY['👨‍🍳 Barista yarışmalarında ödül kazanmış.', '☕ Pour over kahveleri mükemmel.', '🪑 Az oturma yeri var.'], 'Filter Coffee', 3),
    (v_coffee_id, 'Café Lomi', 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800', 'https://maps.google.com/?q=Café+Lomi+Paris', 'https://www.cafelomi.com/', 48.891, 2.364, 4.5, 1800, 'Kendi kavurdukları kahvelerle tanınan, geniş ve rahat bir mekan.', ARRAY['🏭 Kavurma tesisleri mekanda.', '🍳 Brunch menüsü harika.', '🌳 Bahçesi var, yazın keyifli.'], 'Espresso', 4),
    (v_coffee_id, 'Boot Café', 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800', 'https://maps.google.com/?q=Boot+Café+Paris', 'https://www.bootcafe.fr/', 48.868, 2.379, 4.6, 800, 'Marais''de küçük ve şirin bir kahve dükkanı.', ARRAY['👢 İsmi ''çizme'' demek, dekorasyonu da o temada.', '☕ Flat white''ları çok iyi.', '🥪 Avokado tostu popüler.'], 'Flat White', 5),
    (v_coffee_id, 'Cuppa', 'https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=800', 'https://maps.google.com/?q=Cuppa+Paris', 'https://www.cuppa.fr/', 48.853, 2.376, 4.5, 700, 'Bastille yakınlarında rahat bir kahve dükkanı.', ARRAY['💻 Wifi hızlı, çalışmak için iyi.', '🍪 Ev yapımı kurabiyeler lezzetli.', '☕ Kahve kalitesi tutarlı.'], 'Americano', 6),
    (v_coffee_id, 'Fondation Café', 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800', 'https://maps.google.com/?q=Fondation+Café+Paris', 'https://www.fondationcafe.fr/', 48.869, 2.371, 4.6, 1000, 'Canal kenarında harika bir kahve deneyimi.', ARRAY['🌊 Canal manzarası var.', '☕ Third wave coffee.', '🎨 İç dekorasyonu çok estetik.'], 'Cortado', 7),
    (v_coffee_id, 'Holybelly', 'https://images.unsplash.com/photo-1506619216599-9d16d0903dfd?w=800', 'https://maps.google.com/?q=Holybelly+Paris', 'https://www.holybellycafe.com/', 48.873, 2.365, 4.7, 2500, 'Kahve ve brunch için popüler bir mekan.', ARRAY['🥞 Pancake''leri efsane.', '☕ Kahveleri de çok kaliteli.', '⏳ Hafta sonu çok kalabalık.'], 'Flat White & Pancakes', 8),
    (v_coffee_id, 'Fée Nature', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800', 'https://maps.google.com/?q=Fée+Nature+Paris', 'https://www.feenature.fr/', 48.872, 2.368, 4.5, 600, 'Organik ve sağlıklı seçenekler sunan kahve dükkanı.', ARRAY['🌱 Organik ve vegan seçenekler.', '🥗 Sağlıklı yemekler var.', '☕ Kahveleri de organik.'], 'Oat Milk Latte', 9),
    (v_coffee_id, 'Season', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Season+Paris', 'https://www.season-paris.fr/', 48.869, 2.358, 4.6, 850, 'Mevsimsel ve taze malzemeler kullanan kahve dükkanı.', ARRAY['🍂 Mevsime göre değişen menü.', '☕ Specialty coffee.', '🥙 Öğle yemeği seçenekleri güzel.'], 'Pour Over', 10),
    (v_coffee_id, 'Café Oberkampf', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', 'https://maps.google.com/?q=Café+Oberkampf', 'https://www.cafeoberkampf.fr/', 48.864, 2.369, 4.5, 950, 'Oberkampf semtindeki yerel favorisi.', ARRAY['🏘️ Mahalle kafesi atmosferi.', '☕ Klasik Fransız kahve kültürü.', '🥐 Sabah kahvaltısı için ideal.'], 'Café Crème', 11);

  -- BISTRO VENUES (11)
  INSERT INTO venues (food_category_id, name, image, map_link, website_url, lat, lng, google_rating, google_review_count, mentor_note, reviews_summary, must_order, sort_order) VALUES
    (v_bistro_id, 'Le Comptoir du Relais', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', 'https://maps.google.com/?q=Le+Comptoir+du+Relais', 'https://www.hotel-paris-relais-saint-germain.com/', 48.853, 2.338, 4.5, 2000, 'Şef Yves Camdeborde''un efsanevi bistrosu. Rezervasyonsuz, sıra beklemeye değer.', ARRAY['💯 Öğle yemeği menüsü inanılmaz popüler.', '🍷 Harika şarap listesi.', '⏳ Sıra beklemeye hazır olun.'], 'Menu du Jour', 1),
    (v_bistro_id, 'Bistrot Paul Bert', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Bistrot+Paul+Bert', 'https://www.bistrotpaulbert.com/', 48.852, 2.379, 4.6, 1800, 'Klasik Fransız bistro deneyiminin zirvesi.', ARRAY['🥩 Steak frites mükemmel.', '🍮 Tatlıları unutulmaz.', '🍷 Şarap seçimi zengin.'], 'Steak Frites', 2),
    (v_bistro_id, 'Chez L''Ami Jean', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800', 'https://maps.google.com/?q=Chez+L''Ami+Jean', 'https://www.lamijean.fr/', 48.858, 2.308, 4.5, 1500, 'Basque mutfağından etkilenen, cömert porsiyonlu bistro.', ARRAY['🍖 Porsiyon ne o, inanılmaz cömert.', '🇪🇸 Basque etkileri güçlü.', '🎉 Atmosfer çok canlı ve eğlenceli.'], 'Riz au Lait', 3),
    (v_bistro_id, 'Le Baratin', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', 'https://maps.google.com/?q=Le+Baratin+Paris', 'https://www.lebaratin.fr/', 48.871, 2.387, 4.4, 900, 'Belleville''deki yerel favorisi, otantik Paris bistrosu.', ARRAY['🏘️ Turistik değil, çok yerel.', '🍷 Natural wine listesi harika.', '👩‍🍳 Şef Raquel''in yaratıcı mutfağı.'], 'Plat du Jour', 4),
    (v_bistro_id, 'Aux Prés', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Aux+Prés+Paris', 'https://www.auxpres.com/', 48.855, 2.334, 4.5, 1200, 'Cyril Lignac''ın modern bistrosu, Saint-Germain''de.', ARRAY['👨‍🍳 Ünlü şef Cyril Lignac''ın mutfağı.', '🎨 Dekorasyon çok şık.', '🍽️ Klasik yemeklere modern dokunuş.'], 'Boeuf Bourguignon', 5),
    (v_bistro_id, 'Clown Bar', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', 'https://maps.google.com/?q=Clown+Bar+Paris', 'https://www.clownbar-paris.fr/', 48.865, 2.369, 4.6, 1000, 'Eski bir sirk dekorasyonunda, yaratıcı bistro mutfağı.', ARRAY['🎪 Sirk temalı dekorasyon çok ilginç.', '🍷 Natural wine seçimi güzel.', '🍽️ Yaratıcı ve lezzetli yemekler.'], 'Seasonal Menu', 6),
    (v_bistro_id, 'Le Petit Cler', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800', 'https://maps.google.com/?q=Le+Petit+Cler', 'https://www.lepetitcler.fr/', 48.857, 2.307, 4.4, 800, '7. bölgedeki samimi mahalle bistrosu.', ARRAY['🏘️ Yerel atmosfer.', '💰 Fiyatları makul.', '🥖 Klasik Fransız bistro yemekleri.'], 'Poulet Rôti', 7),
    (v_bistro_id, 'Bouillon Pigalle', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Bouillon+Pigalle', 'https://www.bouillonpigalle.com/', 48.883, 2.338, 4.3, 3500, 'Uygun fiyatlı, geleneksel Fransız mutfağı. Art deco dekorasyon.', ARRAY['💰 Çok uygun fiyatlar.', '🏛️ Tarihi art deco binası muhteşem.', '⏳ Sıra olabiliyor ama hızlı dönüş var.'], 'Escargots', 8),
    (v_bistro_id, 'Le Pantruche', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', 'https://maps.google.com/?q=Le+Pantruche', 'https://www.lepantruche.com/', 48.878, 2.342, 4.6, 700, '9. bölgede gizli bir cevher, harika bistro.', ARRAY['🤫 Turistlerin pek bilmediği yerel bir yer.', '🍽️ Mevsimsel menü.', '👍 Fiyat/performans mükemmel.'], 'Market Menu', 9),
    (v_bistro_id, 'Astier', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800', 'https://maps.google.com/?q=Astier+Paris', 'https://www.restaurant-astier.com/', 48.868, 2.370, 4.5, 900, 'Klasik bistro, peynir arabasıyla ünlü.', ARRAY['🧀 Peynir arabası geleneği harika.', '🍷 Şarap listesi uzun.', '💯 Gerçek Paris bistro deneyimi.'], 'Menu + Fromage', 10),
    (v_bistro_id, 'Le Severo', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Le+Severo', 'https://www.lesevero.fr/', 48.832, 2.323, 4.7, 600, 'Et tutkunları için mükemmel bir bistro.', ARRAY['🥩 Et kalitesi inanılmaz.', '🔪 Kasaptan taze geliyormuş.', '📅 Rezervasyon şart.'], 'Côte de Boeuf', 11);

  -- CREPE VENUES (11)
  INSERT INTO venues (food_category_id, name, image, map_link, website_url, lat, lng, google_rating, google_review_count, mentor_note, reviews_summary, must_order, sort_order) VALUES
    (v_crepe_id, 'Breizh Café', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800', 'https://maps.google.com/?q=Breizh+Café+Paris', 'https://breizhcafe.com/', 48.86, 2.36, 4.6, 4000, 'Brittany bölgesinin otantik galette''lerini sunan modern mekan.', ARRAY['🥞 Karabuğday unundan yapılan galette''ler mükemmel.', '🍏 Kendi cider''ları harika gidiyor.', '📅 Rezervasyon şart.'], 'Galette Complète', 1),
    (v_crepe_id, 'Little Breizh', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Little+Breizh+Paris', 'https://www.littlebreizh.fr/', 48.868, 2.355, 4.5, 1500, 'Breizh Café''nin kardeş konsepti, daha rahat.', ARRAY['🥞 Aynı kalite, daha az bekleme.', '💰 Fiyatlar uygun.', '🏃 Paket servis de yapıyorlar.'], 'Galette Andouille', 2),
    (v_crepe_id, 'Crêperie Josselin', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800', 'https://maps.google.com/?q=Crêperie+Josselin', 'https://www.creperie-josselin.com/', 48.842, 2.324, 4.5, 2800, 'Montparnasse''daki geleneksel ve samimi krep evi.', ARRAY['🏛️ Klasik Breton krep evi atmosferi.', '🥞 Hem tuzlu hem tatlı çeşitleri harika.', '👨‍👩‍👧 Aile dostu.'], 'Galette Saucisse', 3),
    (v_crepe_id, 'Crêperie Bretonne Fleurie', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Crêperie+Bretonne+Fleurie', 'https://www.creperie-fleurie.fr/', 48.846, 2.289, 4.6, 1200, 'Latin Quarter''daki şirin krep evi.', ARRAY['🌸 Dekorasyon çok sevimli.', '🥞 Otantik Breton tarifleri.', '🍏 Cider seçimi geniş.'], 'Crêpe Suzette', 4),
    (v_crepe_id, 'La Crêperie de Josselin', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800', 'https://maps.google.com/?q=La+Crêperie+de+Josselin', 'https://www.josselin.fr/', 48.843, 2.325, 4.4, 1800, 'Uygun fiyatlı ve lezzetli kreplerle ünlü.', ARRAY['💰 Çok makul fiyatlar.', '🥞 Porsiyon ne o, çok doyurucu.', '⏳ Genelde sıra var.'], 'Galette Jambon-Fromage', 5),
    (v_crepe_id, 'Crêperie Suzette', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Crêperie+Suzette', 'https://www.creperie-suzette.com/', 48.869, 2.380, 4.5, 900, 'Le Marais''deki küçük ve şirin krep yeri.', ARRAY['🏘️ Mahalle atmosferi.', '🥞 Taze malzemeler kullanıyorlar.', '🍓 Tatlı kreplerini mutlaka deneyin.'], 'Crêpe Nutella-Banane', 6),
    (v_crepe_id, 'Blé Noir', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800', 'https://maps.google.com/?q=Blé+Noir+Paris', 'https://www.blenoir.fr/', 48.862, 2.356, 4.6, 700, 'Karabuğday (blé noir) konusunda uzman.', ARRAY['🌾 Karabuğday unu kalitesi çok iyi.', '🥞 Galette''ler lezzetli ve sağlıklı.', '🍏 Organik cider seçenekleri var.'], 'Galette Bio', 7),
    (v_crepe_id, 'Crêperie Genia', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Crêperie+Genia', 'https://www.creperiegenia.fr/', 48.873, 2.347, 4.4, 800, 'Yerel halkın favorisi, sade ve lezzetli.', ARRAY['🏘️ Turistik olmayan bir yer.', '💰 Uygun fiyatlar.', '🥞 Klasik tarifler.'], 'Galette Oeuf-Fromage', 8),
    (v_crepe_id, 'Chez Nénesse', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800', 'https://maps.google.com/?q=Chez+Nénesse', 'https://www.cheznenesse.fr/', 48.866, 2.368, 4.5, 1100, 'Otantik Breton krep evi.', ARRAY['👴 Yaşlı bir çift işletiyor, çok samimi.', '🥞 Geleneksel tarifler.', '🍏 Ev yapımı cider.'], 'Galette Complète', 9),
    (v_crepe_id, 'La Crêpe Rit du Clown', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=La+Crêpe+Rit+du+Clown', 'https://www.lacrepe.fr/', 48.869, 2.372, 4.3, 650, 'Eğlenceli ve neşeli bir krep yeri.', ARRAY['🎪 İsmi kelime oyunu (''krep güler'').', '🥞 Yaratıcı kombinasyonlar deniyorlar.', '👨‍👩‍👧‍👦 Çocuklarla gelmek için güzel.'], 'Crêpe Caramel Beurre Salé', 10),
    (v_crepe_id, 'Crêperie Plougastel', 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800', 'https://maps.google.com/?q=Crêperie+Plougastel', 'https://www.plougastel.fr/', 48.838, 2.335, 4.6, 550, 'Klasik Breton krep evi, aile işletmesi.', ARRAY['👨‍👩‍👧 3 kuşaktır aynı aile işletiyor.', '🥞 Tarifler dededen kalma.', '💯 Çok otantik.'], 'Galette aux Champignons', 11);

  -- MICHELIN VENUES (11) 
  INSERT INTO venues (food_category_id, name, image, map_link, website_url, lat, lng, google_rating, google_review_count, mentor_note, reviews_summary, must_order, sort_order) VALUES
    (v_michelin_id, 'Septime', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', 'https://maps.google.com/?q=Septime+Paris', 'https://www.septime-charonne.fr/', 48.852, 2.38, 4.7, 1500, 'Modern, rahat ve cool bir Michelin deneyimi. Mevsimsel tadım menüleri.', ARRAY['🌱 Malzemelerin tazeliği inanılmaz.', '🍷 Doğal şarap eşleşmeleri başarılı.', '📅 Rezervasyon neredeyse imkansız.'], 'Menu Dégustation', 1),
    (v_michelin_id, 'L''Arpège', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800', 'https://maps.google.com/?q=L''Arpège+Paris', 'https://www.alain-passard.com/', 48.856, 2.315, 4.6, 800, 'Alain Passard''ın 3 Michelin yıldızlı sebze odaklı restoranı.', ARRAY['⭐⭐⭐ 3 Michelin yıldızı.', '🥬 Sebzeler kendi bahçelerinden geliyor.', '💎 Lüks ve unutulmaz bir deneyim.'], 'Menu Légumes', 2),
    (v_michelin_id, 'Le Cinq', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Le+Cinq+Paris', 'https://www.fourseasons.com/paris/dining/', 48.868, 2.302, 4.7, 600, 'Four Seasons''daki 3 yıldızlı ultra-lüks restoran.', ARRAY['⭐⭐⭐ Christian Le Squer''in mutfağı.', '🏰 Saray gibi dekorasyon.', '💰 Çok pahalı ama deneyim eşsiz.'], 'Menu Prestige', 3),
    (v_michelin_id, 'Guy Savoy', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', 'https://maps.google.com/?q=Guy+Savoy+Paris', 'https://www.guysavoy.com/', 48.858, 2.329, 4.6, 500, 'Seine kenarında, 3 Michelin yıldızlı klasik.', ARRAY['⭐⭐⭐ Klasik Fransız haute cuisine.', '🍄 Artichoke çorbası efsane.', '🌊 Nehir manzarası muhteşem.'], 'Soupe d''Artichaut', 4),
    (v_michelin_id, 'Alléno Paris', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800', 'https://maps.google.com/?q=Alléno+Paris', 'https://www.yannick-alleno.com/', 48.866, 2.308, 4.8, 400, 'Yannick Alléno''nun 3 yıldızlı restoranı, modern Fransız.', ARRAY['⭐⭐⭐ Sos tekniği dünya klasmanında.', '🎨 Her tabak bir sanat eseri.', '🍷 Şarap mahzeni inanılmaz.'], 'Menu Découverte', 5),
    (v_michelin_id, 'Le Meurice', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Le+Meurice+Alain+Ducasse', 'https://www.alainducasse-meurice.com/', 48.865, 2.328, 4.7, 700, 'Alain Ducasse''ın 2 Michelin yıldızlı restoranı.', ARRAY['⭐⭐ Versailles esintili dekorasyon.', '👨‍🍳 Alain Ducasse''ın usta mutfağı.', '🎩 Dress code var.'], 'Menu Collection', 6),
    (v_michelin_id, 'Astrance', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', 'https://maps.google.com/?q=Astrance+Paris', 'https://www.astrancerestaurant.com/', 48.862, 2.294, 4.8, 350, 'Pascal Barbot''un 3 Michelin yıldızlı, sadece 25 kişilik küçük restoranı.', ARRAY['⭐⭐⭐ Çok sınırlı yer, rezervasyon zor.', '🎨 Her yemek sürpriz.', '💯 Etkileyici teknik.'], 'Menu Surprise', 7),
    (v_michelin_id, 'Pierre Gagnaire', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800', 'https://maps.google.com/?q=Pierre+Gagnaire+Paris', 'https://www.pierre-gagnaire.com/', 48.871, 2.303, 4.6, 600, '3 Michelin yıldızlı, avangart mutfak.', ARRAY['⭐⭐⭐ Çok yaratıcı ve cesur tatlar.', '🎭 Şef bir sanatçı gibi.', '🍽️ Her tabakta çok sayıda element.'], 'Menu Dégustation', 8),
    (v_michelin_id, 'Le Pré Catelan', 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800', 'https://maps.google.com/?q=Le+Pré+Catelan', 'https://www.leprecatelan.com/', 48.862, 2.249, 4.6, 450, 'Bois de Boulogne''daki 3 Michelin yıldızlı restoran.', ARRAY['⭐⭐⭐ Doğanın içinde yemek deneyimi.', '🌳 Bahçe manzarası harika.', '🍽️ Frédéric Anton''un klasik mutfağı.'], 'Menu Jardin', 9),
    (v_michelin_id, 'Epicure', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', 'https://maps.google.com/?q=Epicure+Paris', 'https://www.epicure-bristol.com/', 48.871, 2.313, 4.7, 550, 'Le Bristol''daki 3 Michelin yıldızlı, Eric Frechon''un mutfağı.', ARRAY['⭐⭐⭐ Macaroni aux truffes efsane.', '🏨 5 yıldızlı otelin restoranı.', '💎 Ultra-lüks deneyim.'], 'Macaroni aux Truffes', 10),
    (v_michelin_id, 'David Toutain', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800', 'https://maps.google.com/?q=David+Toutain+Paris', 'https://www.davidtoutain.com/', 48.856, 2.316, 4.7, 650, '2 Michelin yıldızlı, genç şefin yaratıcı mutfağı.', ARRAY['⭐⭐ Çok yaratıcı ve modern.', '🌱 Sebze odaklı ama et de var.', '👨‍🍳 David Toutain yükselen yıldız.'], 'Seasonal Tasting', 11);

  -- LOCAL SPECIALTIES (11)
  INSERT INTO venues (food_category_id, name, image, map_link, website_url, lat, lng, google_rating, google_review_count, mentor_note, reviews_summary, must_order, sort_order) VALUES
    (v_local_id, 'Soğan Çorbası @ Au Pied de Cochon', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800', 'https://maps.google.com/?q=Au+Pied+de+Cochon', 'https://www.pieddecochon.com/', 48.863, 2.347, 4.4, 6000, '7/24 açık, Paris''in en meşhur soğan çorbasını yapan tarihi brasserie.', ARRAY['🧅 Üzerindeki bol peynir harika.', '🐷 Domuz paçası da spesiyaliteleri.', '🏛️ Eski Paris atmosferi.'], 'Soupe à l''Oignon', 1),
    (v_local_id, 'Makaron @ Pierre Hermé', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800', 'https://maps.google.com/?q=Pierre+Hermé+Paris', 'https://www.pierreherme.com/', 48.851, 2.33, 4.6, 3000, 'Makaronun Picasso''su Pierre Hermé''nin butiği.', ARRAY['🌹 Ispahan (gül, ahududu, liçi) ikonik.', '🍫 Mogador (çikolata, tutku meyvesi) klasik.', '🎁 Kutular sanat eseri.'], 'Ispahan Macaron', 2),
    (v_local_id, 'Croissant @ Blé Sucré', 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800', 'https://maps.google.com/?q=Blé+Sucré', 'https://www.blesucre.com/', 48.846, 2.377, 4.7, 1600, 'Paris''in en iyi croissant''larından biri.', ARRAY['🥐 Tereyağlı, kat kat, mükemmel.', '👨‍🍳 Fabrice Le Bourdat''nın hassas işçiliği.', '⏰ Sabah erken gidin, hemen bitiyor.'], 'Croissant au Beurre', 3),
    (v_local_id, 'Steak Frites @ Le Relais de l''Entrecôte', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800', 'https://maps.google.com/?q=Le+Relais+de+l''Entrecôte', 'https://www.relaisentrecote.fr/', 48.854, 2.329, 4.4, 5000, 'Menüsü yok, sadece steak-frites yapan efsane zincir.', ARRAY['🥩 Gizli sos tarifi kimse bilmiyor.', '🍟 Unlimited patates.', '⏳ Sıra her zaman var ama değer.'], 'Steak-Frites + Sauce', 4),
    (v_local_id, 'Escargot @ L''Escargot Montorgueil', 'https://images.unsplash.com/photo-1589476701771-ee4e18f49d17?w=800', 'https://maps.google.com/?q=L''Escargot+Montorgueil', 'https://www.escargot-montorgueil.com/', 48.864, 2.347, 4.3, 2500, '1832''den beri aynı yerde, salyangoz uzmanı.', ARRAY['🐌 En klasik Fransız deneyimi.', '🧄 Sarımsaklı tereyağ sos harika.', '🏛️ Tarihi bina çok etkileyici.'], 'Escargots de Bourgogne', 5),
    (v_local_id, 'Croque Monsieur @ Café de Flore', 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800', 'https://maps.google.com/?q=Café+de+Flore', 'https://www.cafedeflore.fr/', 48.854, 2.332, 4.3, 8000, 'Efsanevi Saint-Germain kafesi, Sartre ve Camus burada takılırdı.', ARRAY['🏛️ Tarihi ve kültürel önemi çok büyük.', '🥪 Croque Monsieur klasik.', '💰 Turistik ve pahalı ama deneyim için değer.'], 'Croque Monsieur', 6),
    (v_local_id, 'Falafel @ L''As du Fallafel', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800', 'https://maps.google.com/?q=L''As+du+Fallafel', 'https://www.lasdufallafel.com/', 48.857, 2.360, 4.4, 12000, 'Le Marais''deki dünyaca ünlü falafel dükkanı.', ARRAY['🥙 Dünyanın en iyi falafel''i tartışması var.', '🌯 Cömert porsiyonlar.', '⏳ Sıra hep var ama hızlı ilerliyor.'], 'Special Fallafel', 7),
    (v_local_id, 'Boeuf Bourguignon @ Chez Dumonet', 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800', 'https://maps.google.com/?q=Chez+Dumonet', 'https://www.josephine-dumonet.com/', 48.850, 2.329, 4.6, 1200, 'Klasik Fransız yemeklerinin en iyisini yapan bistro.', ARRAY['🍖 Boeuf Bourguignon muhteşem.', '💯 Porsiyonlar çok cömert.', '📅 Rezervasyon şart.'], 'Boeuf Bourguignon', 8),
    (v_local_id, 'Tarte Tatin @ La Poule au Pot', 'https://images.unsplash.com/photo-1589476701771-ee4e18f49d17?w=800', 'https://maps.google.com/?q=La+Poule+au+Pot', 'https://www.lapouleaupot.com/', 48.863, 2.345, 4.4, 1500, 'Romantik, mum ışıklı klasik bistro. Tersten elmalı tart ünlü.', ARRAY['🕯️ Mum ışığı ve romantik atmosfer.', '🍎 Tarte Tatin (tersten elmalı tart) meşhur.', '💑 Çiftler için ideal.'], 'Tarte Tatin', 9),
    (v_local_id, 'Quiche Lorraine @ Chez Janou', 'https://images.unsplash.com/photo-1588013273468-315fd88ea34c?w=800', 'https://maps.google.com/?q=Chez+Janou', 'https://www.chezjanou.com/', 48.856, 2.364, 4.5, 2200, 'Provence mutfağı yapan, pastis sevgisi ile ünlü bistro.', ARRAY['🥧 Quiche Lorraine mükemmel.', '🍸 87 çeşit pastis var.', '🌿 Provence atmosferi.'], 'Quiche Lorraine', 10),
    (v_local_id, 'Mille-Feuille @ Carl Marletti', 'https://images.unsplash.com/photo-1587241321921-91a834d82360?w=800', 'https://maps.google.com/?q=Carl+Marletti', 'https://www.carlmarletti.com/', 48.844, 2.361, 4.7, 900, 'Patisserie ustası Carl Marletti''nin dükkanı.', ARRAY['🍰 Mille-Feuille (Napoleon) Paris''in en iyisi.', '🎨 Her pasta bir sanat eseri.', '💎 Fiyatlar premium ama değer.'], 'Mille-Feuille Vanille', 11);

END $$;
